name: 'Initialize Bit'
description: 'Initialize Bit'
branding:
  icon: 'download'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
    default: './'
  cache:
    description: "Enable caching"
    required: false
    default: 'false'
  ripple:
    description: "Use Ripple CI to build components"
    required: false
    default: 'false'
  log:
    description: "Log options for bit commands. Options: [trace, debug, info, warn, error, fatal]"
    required: false
    default: 'info'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      if: inputs.cache == 'true'
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      if: inputs.cache == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Run Bit Initialization Script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        WSDIR: ${{ inputs.ws-dir }}
        CACHE: ${{ inputs.cache }}
        RIPPLE: ${{ inputs.ripple }}
        LOG: ${{ inputs.log }}
