name: 'Initialize Bit'
description: 'Initialize Bit'
branding:
  icon: 'download'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
    default: './'
  cache:
    description: "Enable cache"
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get npm global path
      if: inputs.cache == 'true'
      shell: bash
      id: npm-global-path
      run: echo "NPM_GLOBAL_PATH=$(npm root -g)" >> $GITHUB_ENV

    - name: Cache npm global packages
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.NPM_GLOBAL_PATH }}
        key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-global-

    - name: Install pnpm
      if: inputs.cache == 'true'
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      if: inputs.cache == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Run Bit Initialization Script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        WS_DIR: ${{ inputs.ws-dir }}
