name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      # - name: Test
      #   id: npm-ci-test
      #   run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          ws-dir: "test-data"
          BIT_CLOUD_ACCESS_TOKEN: ${{ secrets.BIT_CLOUD_ACCESS_TOKEN }}
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}

      - name: Resolve component packages from bit.cloud registry (Mandatory for component installation using package managers other than Bit)
        run: |
          npm config set '@bit:registry' https://node-registry.bit.cloud
          npm config set '@teambit:registry' https://node-registry.bit.cloud
          npm config set //node-registry.bit.cloud/:_authToken ${{ env.BIT_CLOUD_ACCESS_TOKEN }}
      - name: Installed Node version test
        run: |
            node -v
      - name: Installed Bit version test
        run: |
          bit -v
      - name: Installed Bit location test
        run: |
          which bit
      - name: Bit token test
        run: echo "$(bit config get user.token)"
      - name: Bit workspace directory environment variable test
        run: |
          echo $WSDIR
      - name: Bit org environment variable test
        run: |
          echo $ORG
      - name: Bit scope environment variable test
        run: |
          echo $SCOPE
      - name: Bit analytics reporting environment variable test
        run: |
          echo $BIT_CONFIG_ANALYTICS_REPORTING
      - name: Bit anonymous reporting environment variable test
        run: |
          echo $BIT_CONFIG_ANONYMOUS_REPORTING
      - name: Bit interactive environment variable test
        run: |
          echo $BIT_CONFIG_INTERACTIVE
      - name: Bit user token environment variable test
        run: |
          echo $BIT_CLOUD_ACCESS_TOKEN
      - name: Bit path environment variable test
        run: |
          echo $PATH
