name: Docker Init Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:latest
      options: --user root
    timeout-minutes: 20
    env:
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
      NODE_OPTIONS: --max-old-space-size=6656 # set max old space size to 6.5GiB, GitHub hosted runners have 7GiB
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create symlink to _w directory
        run: |
          mkdir -p /home/runner/work/_actions/bit-tasks
          ln -sfn /__w/_actions/bit-tasks /home/runner/work/_actions/bit-tasks
      - name: Initialize Bit
        uses: bit-tasks/init@main
        with:
          ws-dir: "test-data"
          log: "trace"
