name: Test Bit Init with Docker Alpine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:latest-alpine
      options: --user root
    timeout-minutes: 20
    env:
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Create symlink to _w directory
        run: |
          mkdir -p /home/runner
          ln -sfn /__w /home/runner/work
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify Node.js installation
        run: node -v
      - name: Initialize Bit
        uses: bit-tasks/init@main
        with:
          ws-dir: "test-data"
          docker: "true"
          # ripple: "true"
          log: "trace"
          # cache: "true"
        continue-on-error: true
      - name: Search for index.js in main/dist directory pattern
        run: |
          echo "Searching for main/dist/index.js..."
          find / -type f -path "*/main/dist/index.js"
      - name: List files in init directory
        run: |
          echo "Listing files in /home/runner/work/_actions/bit-tasks/init:"
          ls -al /home/runner/work/_actions/bit-tasks/init
      - name: List files in main directory
        run: |
          echo "Listing files in /home/runner/work/_actions/bit-tasks/init/main:"
          ls -al /home/runner/work/_actions/bit-tasks/init/main
      - name: List files in dist directory
        run: |
          echo "Listing files in /home/runner/work/_actions/bit-tasks/init/main/dist:"
          ls -al /home/runner/work/_actions/bit-tasks/init/main/dist
      - name: List files in root dist directory
        run: |
          echo "Listing files in /__w/_actions/bit-tasks/init/main/dist:"
          ls -al /__w/_actions/bit-tasks/init/main/dist
      # - name: Resolve component packages from bit.cloud registry (Mandatory for component installation using package managers other than Bit)
      #   run: |
      #     npm config set '@bit:registry' https://node-registry.bit.cloud
      #     npm config set '@teambit:registry' https://node-registry.bit.cloud
      #     npm config set //node-registry.bit.cloud/:_authToken ${{ env.BIT_CONFIG_ACCESS_TOKEN }}
      # - name: Installed Node version test
      #   run: |
      #       node -v
      # - name: Installed Bit version test
      #   run: |
      #     bit -v
      # - name: Installed Bit location test
      #   run: |
      #     which bit
      # - name: Bit token test
      #   run: echo "$(bit config get user.token)"
      # - name: Bit workspace directory environment variable test
      #   run: |
      #     echo $WSDIR
      # - name: Ripple CI environment variable test
      #   run: |
      #     echo $RIPPLE
      # - name: Log environment variable test
      #   run: |
      #     echo $LOG
      # - name: Cache environment variable test
      #   run: |
      #     echo $CACHE
      # - name: Bit org environment variable test
      #   run: |
      #     echo $ORG
      # - name: Bit scope environment variable test
      #   run: |
      #     echo $SCOPE
      # - name: Bit analytics reporting environment variable test
      #   run: |
      #     echo $BIT_CONFIG_ANALYTICS_REPORTING
      # - name: Bit anonymous reporting environment variable test
      #   run: |
      #     echo $BIT_CONFIG_ANONYMOUS_REPORTING
      # - name: Bit interactive environment variable test
      #   run: |
      #     echo $BIT_CONFIG_INTERACTIVE
      # - name: Bit user token environment variable test
      #   run: |
      #     echo $BIT_CONFIG_ACCESS_TOKEN
      # - name: Bit path environment variable test
      #   run: |
      #     echo $PATH
      # - name: Bit console environment variable test
      #   run: |
      #     echo $BIT_DISABLE_CONSOLE
      # - name: Bit spinner environment variable test
      #   run: |
      #     echo $BIT_DISABLE_SPINNER
